FROM node:16-alpine3.15 as dependencies
WORKDIR /app
COPY package*.json ./
COPY yarn.lock ./
RUN export NODE_OPTIONS=--max_old_space_size=4096
RUN apk add --no-cache \
    sudo \
    curl \
    build-base \
    g++ \
    libpng \
    libpng-dev \
    jpeg-dev \
    pango-dev \
    cairo-dev \
    giflib-dev \
    python3
RUN yarn install

EXPOSE 4007
CMD ["npm", "run", "start:dev"]
