export const MAX_LENGTH_USER_ID = 9;
export const DEFAULT_LIMIT = 10;
export const DEFAULT_OFFSET = 0;
export const USER_PASSWORD_MIN_LENGTH = 6;
export const USER_PASSWORD_MAX_LENGTH = 128;
export const SALT_ROUND = 10;
export const EXPIRE_TIME_MINUTE = 5;
export const MAX_LENGTH_VERIFICATION_CODE = 6;
export const LIMIT_REGISTER_ACCOUNT = 10;
export const LIMIT_LOGIN_FAILED = 5;
export const REDIS_PREFIX = {
  FORGOT_PASSWORD: 'FORGOT_',
  REGISTER_USER: 'REGISTER_',
  LOGIN_FAILED: 'LOGIN_FAILED_',
  EXCHANGE_TOKEN: 'EXCHANGE_TOKEN_',
  VERIFICATION_CODE: 'VERIFICATION_CODE_',
  VERIFICATION_CHANGE_EMAIL_CODE: 'VERIFICATION_CHANGE_EMAIL_CODE_',
  VERIFICATION_LOGIN_CODE: 'VERIFICATION_LOGIN_CODE_',
  VERIFICATION_CHANGE_PASSWORD_CODE: 'VERIFICATION_CHANGE_PASSWORD_CODE_',
  VERIFICATION_SENT_EMAIL_OTP: 'VERIFICATION_SENT_EMAIL_OTP_',
};
export enum MAIL_TEMPLATES {
  IDENTITY_VERIFY_EMAIL = 'verify-email',
}

export enum MAIL_GUN {
  FROM_EMAIL = 'mike@mikedutuandu.com',
  FROM_TITLE = 'Quiz App',
}

export const LIMIT_SEND_EMAIL_OTP = 20;
export const LIMIT_VERIFY_OTP = 5;

export const LIMIT_LOGIN = 10;
